version: '3.7'

services:
  cobalt-api:
    image: ghcr.io/abdullahdagoat/cobalt
    restart: unless-stopped
    container_name: cobalt-api
    init: true
    tty: true
    ports:
      - 127.0.0.1:9000:9000
    environment:
      API_URL: "https://xtract.gobly.ru/"
      API_NAME: "xtractor"
    labels:
      - com.centurylinklabs.watchtower.scope=cobalt

  watchtower:
    image: ghcr.io/containrrr/watchtower
    restart: unless-stopped
    command: --cleanup --scope cobalt --interval 900 --include-restarting
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock